apiVersion: v1
kind: ServiceAccount
metadata:
  name: ajmal-trial-us-01-hello-sa
  namespace: ajmal-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::443245368846:role/Devlift-PlatformAccess
  labels:
    app: ajmal-trial-us-01-hello
    app.kubernetes.io/name: ajmal-trial-us-01-hello
    app.kubernetes.io/instance: ajmal-trial-us-01-hello-stage
    app.kubernetes.io/managed-by: devlift
