apiVersion: v1
kind: Service
metadata:
  name: ajmal-trial-us-01-testig-service
  namespace: ajmal-ns
  labels:
    app: ajmal-trial-us-01-testig
spec:
  type: ClusterIP
  selector:
    app: ajmal-trial-us-01-testig
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
